MODELO_OLLAMA = "novaforgeai/gemma2:2b-optimized"
TERMINOS_DE_BUSQUEDA = 30
OLLAMA_TAGS_URL = "http://localhost:11434/api/tags"

TECLA_ACTIVACION = "ç"
TECLA_FINALIZACION = "ñ"

ESPERA_MIN_SEGUNDOS = 1
ESPERA_MAX_SEGUNDOS = 10
TAB_MIN = 1
TAB_MAX = 5
